name: Android CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install firebase cli
      run: |
        #node@12 linking conflicts w/ firebase-cli dependency. Unlink first.
        brew unlink node@12
        brew install firebase-cli
    - name: Install gems
      run: bundle install
    - name: Test
      run: bundle exec fastlane test
    - name: Distribute
      run: bundle exec fastlane distribute
